config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'
  get '/users/edit' => 'users#edit'

  resources :users, :only => [:new, :create, :update, :index, :show]
  resources :categories
  resources :images

  post '/images/:image_id/likes' => 'likes#create', :as => 'likes'
  delete '/images/:image_id/likes' => 'likes#destroy'


  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  title       :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  cover_image :text
#

class Category < ActiveRecord::Base
  has_many :users
  has_and_belongs_to_many :images

  def self.search(search)
  if search
    find(:all, :conditions => ['category LIKE ?', "%#{search}%"])
  else
    all
  end
end
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  url        :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  latitude   :float
#  longitude  :float
#

class Image < ActiveRecord::Base
  has_many :likes
  belongs_to :user
  has_and_belongs_to_many :categories

  def like_count
    self.likes.count
  end

end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :integer          not null, primary key
#  image_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Like < ActiveRecord::Base
belongs_to :user
belongs_to :image

# validate :user_does_not_already_like_post

def user_does_not_already_like_image
  errors.add(:user, "You can only like a post once.") if user.already_likes?(image)
end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  avatar          :text
#  admin           :boolean          default("false")
#  name            :text
#  username        :text
#  bio             :text
#

class User < ActiveRecord::Base
  has_many :images
  has_many :categories, :through => :images
  has_many :likes
  has_secure_password


  validates :email, :presence => true, :uniqueness => true, :length => {:minimum => 5}

  def already_likes?(image)
    # self.likes.find(:all, :condition => ['image_id = ?', image.id]).size > 0
    # self.likes.where(:all, :condition => ['image_id = ?', image.id]).size > 0

    puts "======================", self.id, image.id, self.likes.where('image_id = ?', image.id).inspect

    self.likes.where('image_id = ?', image.id).size > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user

  private

  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_if_logged_in
    redirect_to login_path unless @current_user.present?
  end

  def check_if_admin
    redirect_to root_path unless (@current_user.present? && @current_user.admin?)
  end
      

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @categories = Category.new

  end

  def search
    @categories = Category.search(params[:query])
    raise @categories.inspect
  end


  def create
    category = Category.create category_params
    redirect_to category
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    category = Category.find params[:id]
    category.update category_params
    redirect_to category
  end

  def show
    @category = Category.find params[:id]
  end

  def destroy
    category = Category.find params[:id]
    category.destroy
    redirect_to categoties_path
  end


  private
  def category_params
    params.require(:category).permit(:title, :user_id)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @image = Image.all
  end

  def new
    @image = Image.new
    @categories = Category.all
  end

  def create
    image = Image.create #image_params

    if params[:file].present?
     req = Cloudinary::Uploader.upload( params[:file] )
     image.url = req["public_id"]
   end

    image.category_ids = params[:category_ids]
    image.save
    @current_user.images << image
    redirect_to categories_path #image
    # params[:category][:ids].each do |checked_category_id|
    # end

  end

  def edit
    @image = Image.find params[:id]
  end

  def update
    image = Image.find params[:id]

    if params[:file].present?
     req = Cloudinary::Uploader.upload( params[:file] )
     image.url = req["public_id"]
   end

    image.update_attributes image_params
    image.save

    # TODO: check image saved correctly, or had errors? (if image.save)

    redirect_to image_path
  end

  def show
    @image = Image.find params[:id]
  end

  def destroy
    image = Image.find params[:id]
    image.destroy
    redirect_to image_path
  end


  private
  def image_params
      params.require(:image).permit(:user_id, :url)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

def create
  # raise 'create'
  like = Like.create user_id: @current_user.id, image_id: params[:image_id]
  redirect_to image_path params[:image_id]
end

def destroy
  like = Like.find_by(user_id: @current_user.id, image_id: params[:image_id])
  # raise like.inspect
  like.destroy
  redirect_to image_path params[:image_id]
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
  user = User.find_by :email => params[:email]
  if user.present? && user.authenticate( params[:password])
    # flash[:welcome] = "Welcom #{user.email}"
    session[:user_id] = user.id
    redirect_to user_path( user )
  else
    flash[:error] = "Invalid email or password"
    redirect_to login_path
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_in, :only => [:edit, :update]
  before_action :check_if_admin, :only => [:index]

  def index
    @users = User.all
  end


  def new
    @user = User.new
  end


  def create
    user = User.new user_params

    if params[:file].present?
      req = Cloudinary::Uploader.upload( params[:file] )
      user.avatar = req["public_id"]
    end

    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    # @user = @current_user
  end


  def update
    # raise params.inspect
    user = @current_user

    if params[:file].present?
      req = Cloudinary::Uploader.upload( params[:file] )
      user.avatar = req["public_id"]
    end

    user.update_attributes user_params
    user.save

    redirect_to user_path
  end

  def show
    @user = User.find params[:id]
  end


  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar, :bio, :username, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </fieldset>
  <fieldset>
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </fieldset>

  <fieldset>
    <%= f.label :image %>
    <%= f.url_field :image %>
  </fieldset>

  <fieldset>
    <label></label>
    <%= f.submit %>
  </fieldset>
<% end %>

app/views/categories/edit.html.erb
<h1>Category#edit</h1>
<p>Find me in app/views/category/edit.html.erb</p>

app/views/categories/index.html.erb
<%= render "layouts/header" %>
<div class="container">
  <!-- <h1>Categories</h1> -->
  <br>
  <% @categories.in_groups(3, false).each do |group| %>
    <div class="row">
      <% group.each do |cat| %>
          <div class="col-xs-12 col-md-4 image-container <%= cat.title %>" >
            <%= link_to cat do %>
              <div class="overlay" style="display:relative; text-align:cetnter;">
                <span class="overlay-title" style="position:absolute"><%= cat.title %></span>
                <%= image_tag(cat.cover_image, :class => 'img-responsive', :style => "object-fit: cover; height:350px")  %>
            </div>
            <% end %>
          </div>
      <% end %>
    </div>
  <% end %>
</div>
<div class="sharethis">
  <ul>
    <li><span class='st_sharethis_large' displayText='ShareThis'></span></li>
    <li><span class='st_facebook_large' displayText='Facebook'></span></li>
    <li><span class='st_twitter_large' displayText='Tweet'></span></li>
    <li><span class='st_linkedin_large' displayText='LinkedIn'></span></li>
    <li><span class='st_pinterest_large' displayText='Pinterest'></span></li>
    <li><span class='st_email_large' displayText='Email'></span></li>
  </ul>
</div>

app/views/categories/new.html.erb
<h1>Category#new</h1>
<p>Find me in app/views/category/new.html.erb</p>

app/views/categories/show.html.erb
<%= render "layouts/header" %>
<br>
<div class="container">
<% @category.images.in_groups_of(3, false).each do |group| %>
  <div class="row">
    <% group.each do |img| %>
      <div class="col-xs-12 col-md-4 image-container" >
        <%= link_to image_path(img.id) do %>
          <div class="overlay" style="display:relative; text-align:cetnter;">
            <%= cl_image_tag(img.url, :class => 'img-responsive', :style => "object-fit: cover; height:350px")  %>
        </div>
        <% end %>
      </div>

    <% end %>
  </div>

<% end %>
</div>
<div class="sharethis">
  <ul>
    <li><span class='st_sharethis_large' displayText='ShareThis'></span></li>
    <li><span class='st_facebook_large' displayText='Facebook'></span></li>
    <li><span class='st_twitter_large' displayText='Tweet'></span></li>
    <li><span class='st_linkedin_large' displayText='LinkedIn'></span></li>
    <li><span class='st_pinterest_large' displayText='Pinterest'></span></li>
    <li><span class='st_email_large' displayText='Email'></span></li>
  </ul>
</div>

app/views/images/edit.html.erb
<h1>Images#edit</h1>
<p>Find me in app/views/images/edit.html.erb</p>

<%= f.submit %>
<% end %>

<%= form_for(@image, :html => {:multipart => true} ) do |f| %>

<%= form_for @artist do |f| %>
  

app/views/images/new.html.erb
<%= render "layouts/header" %>
<div class="container">
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <p>Select categories:</p>

      <%= form_for(@image, :html => {:multipart => true} ) do |f| %>
        <% @categories.each do |c| %>
          <%= check_box_tag "category_ids[]", c.id %>
          <%= label_tag c.title %><br>
        <% end %>

        <%= f.cl_image_upload :url, :html => {:required => true} %>
        <%= f.label :location %><br>

        <%= f.submit "Upload", :class => "btn btn-lg btn-primary btn-block"%>
      <% end %>
    </div>
  </div>
</div>
<div class="sharethis">
  <ul>
    <li><span class='st_sharethis_large' displayText='ShareThis'></span></li>
    <li><span class='st_facebook_large' displayText='Facebook'></span></li>
    <li><span class='st_twitter_large' displayText='Tweet'></span></li>
    <li><span class='st_linkedin_large' displayText='LinkedIn'></span></li>
    <li><span class='st_pinterest_large' displayText='Pinterest'></span></li>
    <li><span class='st_email_large' displayText='Email'></span></li>
  </ul>
</div>

app/views/images/show.html.erb
<%= render "layouts/header" %>
<br>
  <div class="container">
    <div class="well well-lg">
      <div class="row">
        <div class="col-md-9">
          <%= cl_image_tag @image.url, :class => 'img-responsive show-image-main'%>
        </div>
        <div class="col-md-offset-1 col-md-2">
          <div class="row show-image-avatar" style="margin-bottom:10px">
            <%= image_tag @image.user.avatar, :style => "border-radius:50%; width:80px; height:80px; border-color:rgba(215,2,64,.7); border-width:3px; border-style:solid" %>
          </div>
          <div class="row show-image-content">
            <div class="col-md-12">
              <div class="row" style="margin-bottom:5px">
                <% if @current_user.present? && @current_user.already_likes?(@image) %>
                   <%=link_to "Unlike", likes_path(@image), :method => 'delete', :style => "color:rgba(215,2,64,.7)"  %>
                 <% else %>
                   <%= link_to "Like", likes_path(@image), :method => 'post', :style => "color:rgba(215,2,64,.7)" %>
                <% end %>

                <% if @image.like_count > 0 %>
                  <p>Likes: <%=  @image.like_count %></p>
                <% end %>
              </div>
              <div class="row" style="margin-bottom:5px">
                Taken at: <span style="color:rgba(215,2,64,.7)"><%= @image.created_at.strftime("%B %d %Y, %l:%M%P") %></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="sharethis">
  <ul>
    <li><span class='st_sharethis_large' displayText='ShareThis'></span></li>
    <li><span class='st_facebook_large' displayText='Facebook'></span></li>
    <li><span class='st_twitter_large' displayText='Tweet'></span></li>
    <li><span class='st_linkedin_large' displayText='LinkedIn'></span></li>
    <li><span class='st_pinterest_large' displayText='Pinterest'></span></li>
    <li><span class='st_email_large' displayText='Email'></span></li>
  </ul>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-default-customized">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <%= link_to "Pro Photo", root_path, :class => "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <!-- <li class="active"><= link_to "Home", root_path ></li> -->
      <li><%= link_to "categories", categories_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if ! @current_user.present? %>
      <li><%= link_to "Join", new_user_path %></li>
      <li><%= link_to "Sign in", login_path %></li>
      <% end %>

      <% if @current_user.present? %>
      <li><%= link_to "Upload a new Photo", new_image_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= cl_image_tag @current_user.avatar, :class => 'nav-avatar' %>
            <%= "#{@current_user.name}" %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Profile", user_path(@current_user) %></li>
            <% if @current_user.present? %>
              <% if @current_user.admin? %>
                <li><%= link_to "All users", users_path %></li>
                <% end %>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", login_path, :method => 'delete' %></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/_homenav.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
<nav class="navbar navbar-default navbar-homepage navbar-fixed-top">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <%= link_to "Pro Photo", root_path, :class => "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "categories", categories_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if ! @current_user.present? %>
      <li><%= link_to "Join", new_user_path %></li>
      <li><%= link_to "Sign in", login_path %></li>
      <% end %>

      <% if @current_user.present? %>
      <li><%= link_to "Upload a new Photo", new_image_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= cl_image_tag @current_user.avatar, :class => 'nav-avatar' %>
            <%= "#{@current_user.name}" %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Profile", user_path(@current_user) %></li>
            <% if @current_user.present? %>
              <% if @current_user.admin? %>
                <li><%= link_to "All users", users_path %></li>
                <% end %>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", login_path, :method => 'delete' %></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pro Photo</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/simplex/bootstrap.min.css" rel="stylesheet" integrity="sha384-C0X5qw1DlkeV0RDunhmi4cUBUkPDTvUqzElcNWm1NI2T4k8tKMZ+wRPQOhZfSJ9N" crossorigin="anonymous">

  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%#= cloudinary_js_config %>
  <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript">var switchTo5x=true;</script>
    <script type="text/javascript" id="st_insights_js" src="https://ws.sharethis.com/button/buttons.js?publisher=6e75c87f-5f60-496f-b962-878346a301d2"></script>
    <script type="text/javascript">stLight.options({publisher: "6e75c87f-5f60-496f-b962-878346a301d2", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
</head>
<body class="<%= params[:controller] %> <%=params[:action]%>">

  <%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<%= render "layouts/homenav" %>
<script>
		document.documentElement.className = 'js';
</script>
<main>
  <!-- Initial markup -->
  <div class="segmenter" style="background-image: url(assets/bg.jpg)"></div>
  <h2 class="trigger-headline trigger-headline--hidden"><span>P</span><span>R</span><span>O</span><span></span><span>P</span><span>H</span><span>O</span><span>T</span><span>O</span></h2>
  <div class="bottom-nav">
    <!-- <button class="btn btn-trigger">Show Effect</button> -->
		<button class="btn btn--trigger">By: Mel</button>
  </div>
</main>
<script src="assets/anime.min.js"></script>
<script src="assets/imagesloaded.pkgd.min.js"></script>
<script src="assets/main.js"></script>
<script>
(function() {
  console.log('hi');
  var headline = document.querySelector('.trigger-headline'),
    trigger = document.querySelector('.btn--trigger'),
    segmenter = new Segmenter(document.querySelector('.segmenter'), {
      pieces: 9,
      animation: {
        duration: 1500,
        easing: 'easeOutQuad',
        delay: 50,
        translateZ: {min: 10, max: 65}
      },
      parallax: true,
      parallaxMovement: {min: 5, max: 10},
      positions: [
        {top: 10, left: 20, width: 20, height: 30},
        {top: 8, left: 35, width: 30, height: 20},
        {top: 25, left: 18, width: 14, height: 25},
        {top: 23, left: 50, width: 20, height: 10},
        {top: 30, left: 65, width: 10, height: 30},
        {top: 48, left: 20, width: 10, height: 13},
        {top: 50, left: 67, width: 10, height: 20}
      ],
      onReady: function() {
				/*
				trigger.classList.remove('btn--hidden');
        trigger.addEventListener('click', function() {
          segmenter.animate();
          headline.classList.remove('trigger-headline--hidden');
          this.classList.add('btn--hidden');
        });
				*/
				segmenter.animate();
				headline.classList.remove('trigger-headline--hidden');
      }
    });
})();
</script>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/session/new.html.erb
<%= render "layouts/header" %>
<div class="container">
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <h1>Sign in</h1>

      <% if flash[:error].present? %>
      <p><%= flash[:error] %></p>
      <%end %>

      <%= form_tag login_path do %>

      <div class="form-group">
        <%= label_tag 'Email' %>
        <%= email_field_tag :email,nil, :class => 'form-control'%>
      </div>
      <div class="form-group">
        <%= label_tag 'Password' %>
        <%= password_field_tag :password ,nil, :class => 'form-control'%>
      </div>
  
      <div style="margin-top:20px">
        <%= submit_tag 'Login', :class => "btn btn-lg btn-primary btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless @current_user? == @user %>
  <div id="follow_form">
  <% if @current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<%= render "layouts/header" %>
<div class="container">
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <h1>Edit Profile</h1>

      <% if @current_user.errors.any? %>
        <ol>
          <% @current_user.errors.ful_message.each do |msg|%>
          <li> <%= msg %></li>
          <%end %>
        </ol>
        <% end %>

        <%= form_for(@current_user, :html => {:multipart => true}) do |f| %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, :class => 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :avatar %>
          <%= f.cl_image_upload :file, :class => 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, :class => 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, :class => 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :bio %><br>
          <%= text_area(:post, :body, cols: 20, rows: 8)%>
        </div>
        <div style="margin-top:20px">
          <%= f.submit :class => "btn btn-lg btn-primary btn-block"%>
        </div>

        <% end %>
    </div>

  </div>

</div>

app/views/users/index.html.erb
<%= render "layouts/header" %>
<div class="container">
  <h1>Users</h1>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
          <tr>

            <th>Image</th>
            <th>Name</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <th scope="row"></th>
              <td><%= image_tag user.avatar, :class => 'avatar'  %></td>
              <td><%= link_to user.name, user_path(user) %></td>
              <td><%= link_to user.email, user_path(user) %></td>
            </tr>
          <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "layouts/header" %>
  <div class="jumbotron">
    <div class="container">
        <div class="row">
          <div class="col-md-2">
            <%= cl_image_tag @user.avatar, :class => 'avatar' %>
          </div>
          <div class="col-md-offset-1 col-md-9">
              <div class="col-md-2 col-xs-6">
                <div class="row">
                  <%= @user.name if @user.name.present? %>
                </div>
                <div class="row">
                  Followers:
                </div>
                <div class="row">
                  Following:
                </div>
              </div>
              <div class="col-md-8 col-xs-6">
                <div class="row">
                  <%= link_to '<button type="button">Edit Profile</button>'.html_safe, users_edit_path %>
                </div>
                <div class="row">
                  0
                </div>
                <div class="row">
                  0
                </div>
              </div>
          </div>
        </div>

    </div>
  </div>

<div class="container">
  <% @user.images.in_groups_of(3, false).each do |group| %>
    <div class="row">
      <!-- <%= group %> -->
      <% group.each do |img| %>
        <div class="col-xs-12 col-md-4 image-container" >
          <%= link_to image_path(img.id) do %>
            <div class="overlay" style="display:relative; text-align:cetnter;">
              <%= cl_image_tag(img.url, :class => 'img-responsive', :style => "object-fit: cover; height:350px")  %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>